# Generated by Django 5.1.2 on 2024-10-30 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_genus',
            fields=[
                ('plant_genus_id', models.AutoField(primary_key=True, serialize=False)),
                ('genus_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('contact_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Саженцы плодовитых деревьев и кустарников', 'Саженцы плодовитых деревьев и кустарников'), ('Саженцы декоративных кустарников и деревьев', 'Саженцы декоративных кустарников и деревьев'), ('Семена и луковицы цветов', 'Семена и луковицы цветов'), ('Семена газонной травы', 'Семена газонной травы')], max_length=50)),
                ('plant_name', models.CharField(max_length=100)),
                ('plant_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.PositiveIntegerField()),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('genus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.plant_genus')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.supplier')),
            ],
        ),
    ]
