# Generated by Django 5.1.2 on 2024-10-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='genus_id',
            new_name='genus',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='supplier_id',
            new_name='supplier',
        ),
    ]
