# Generated by Django 5.1.2 on 2024-10-30 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_genus_id_plant_genus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='genus',
            new_name='genus_id',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='supplier',
            new_name='supplier_id',
        ),
    ]
