# Generated by Django 5.1.2 on 2024-10-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_genus_plant_genus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_genus',
            name='genus_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
