# Generated by Django 5.1.2 on 2024-10-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_rename_genus_id_plant_genus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Саджанці плодових дерев і чагарників', 'Саджанці плодових дерев і чагарників'), ('Саджанці декоративних чагарників і дерев', 'Саджанці декоративних чагарників і дерев'), ('Насіння і цибулини квітів', 'Насіння і цибулини квітів'), ('Насіння газонної трави', 'Насіння газонної трави')], max_length=50),
        ),
    ]
