# Generated by Django 5.1.5 on 2025-02-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_plant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='additional_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
