# Generated by Django 5.1.4 on 2025-01-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipped', 'Відправлено'), ('delivered', 'Доставлено')], default='shipped', max_length=20),
        ),
    ]
